# Generated by Django 5.2.4 on 2025-07-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionformula',
            name='scale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.scale'),
        ),
        migrations.AlterField(
            model_name='excludedquestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question'),
        ),
    ]
